/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegionRouteImport } from './routes/$region'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as VerifyPendingRouteImport } from './routes/verify-pending'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as RegionIndexRouteImport } from './routes/$region.index'
import { Route as RegionAccountRouteImport } from './routes/$region.account'
import { Route as RegionCartRouteImport } from './routes/$region.cart'
import { Route as RegionCheckoutRouteImport } from './routes/$region.checkout'
import { Route as RegionForgotPasswordRouteImport } from './routes/$region.forgot-password'
import { Route as RegionRegisterRouteImport } from './routes/$region.register'
import { Route as RegionResetPasswordRouteImport } from './routes/$region.reset-password'
import { Route as RegionSearchRouteImport } from './routes/$region.search'
import { Route as RegionShopRouteImport } from './routes/$region.shop'
import { Route as RegionSignInRouteImport } from './routes/$region.sign-in'
import { Route as RegionVerifyRouteImport } from './routes/$region.verify'
import { Route as RegionVerifyPendingRouteImport } from './routes/$region.verify-pending'
import { Route as RegionWishlistRouteImport } from './routes/$region.wishlist'
import { Route as AccountAddressesRouteImport } from './routes/account/addresses'
import { Route as AccountOrdersRouteImport } from './routes/account/orders'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountVerifyEmailRouteImport } from './routes/account/verify-email'
import { Route as ApiRevalidateRouteImport } from './routes/api.revalidate'
import { Route as CampaignSlugRouteImport } from './routes/campaign.$slug'
import { Route as CollectionSlugRouteImport } from './routes/collection.$slug'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as OrderConfirmationCodeRouteImport } from './routes/order-confirmation.$code'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as RegionCampaignSlugRouteImport } from './routes/$region.campaign.$slug'
import { Route as RegionCollectionSlugRouteImport } from './routes/$region.collection.$slug'
import { Route as RegionCollectionsSlugRouteImport } from './routes/$region.collections.$slug'
import { Route as RegionOrderConfirmationCodeRouteImport } from './routes/$region.order-confirmation.$code'
import { Route as RegionProductSlugRouteImport } from './routes/$region.product.$slug'
import { Route as RegionProductsSlugRouteImport } from './routes/$region.products.$slug'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders.index'
import { Route as AccountOrdersCodeRouteImport } from './routes/account/orders/$code'
import { Route as CampaignSlugSplatRouteImport } from './routes/campaign.$slug.$'
import { Route as RegionCampaignSlugSplatRouteImport } from './routes/$region.campaign.$slug.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionRoute = RegionRouteImport.update({
  id: '/$region',
  path: '/$region',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyPendingRoute = VerifyPendingRouteImport.update({
  id: '/verify-pending',
  path: '/verify-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionIndexRoute = RegionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegionRoute,
} as any)
const RegionAccountRoute = RegionAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => RegionRoute,
} as any)
const RegionCartRoute = RegionCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => RegionRoute,
} as any)
const RegionCheckoutRoute = RegionCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => RegionRoute,
} as any)
const RegionForgotPasswordRoute = RegionForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => RegionRoute,
} as any)
const RegionRegisterRoute = RegionRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => RegionRoute,
} as any)
const RegionResetPasswordRoute = RegionResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => RegionRoute,
} as any)
const RegionSearchRoute = RegionSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => RegionRoute,
} as any)
const RegionShopRoute = RegionShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => RegionRoute,
} as any)
const RegionSignInRoute = RegionSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => RegionRoute,
} as any)
const RegionVerifyRoute = RegionVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => RegionRoute,
} as any)
const RegionVerifyPendingRoute = RegionVerifyPendingRouteImport.update({
  id: '/verify-pending',
  path: '/verify-pending',
  getParentRoute: () => RegionRoute,
} as any)
const RegionWishlistRoute = RegionWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => RegionRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountVerifyEmailRoute = AccountVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AccountRoute,
} as any)
const ApiRevalidateRoute = ApiRevalidateRouteImport.update({
  id: '/api/revalidate',
  path: '/api/revalidate',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignSlugRoute = CampaignSlugRouteImport.update({
  id: '/campaign/$slug',
  path: '/campaign/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionSlugRoute = CollectionSlugRouteImport.update({
  id: '/collection/$slug',
  path: '/collection/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationCodeRoute = OrderConfirmationCodeRouteImport.update({
  id: '/order-confirmation/$code',
  path: '/order-confirmation/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionCampaignSlugRoute = RegionCampaignSlugRouteImport.update({
  id: '/campaign/$slug',
  path: '/campaign/$slug',
  getParentRoute: () => RegionRoute,
} as any)
const RegionCollectionSlugRoute = RegionCollectionSlugRouteImport.update({
  id: '/collection/$slug',
  path: '/collection/$slug',
  getParentRoute: () => RegionRoute,
} as any)
const RegionCollectionsSlugRoute = RegionCollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => RegionRoute,
} as any)
const RegionOrderConfirmationCodeRoute =
  RegionOrderConfirmationCodeRouteImport.update({
    id: '/order-confirmation/$code',
    path: '/order-confirmation/$code',
    getParentRoute: () => RegionRoute,
  } as any)
const RegionProductSlugRoute = RegionProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => RegionRoute,
} as any)
const RegionProductsSlugRoute = RegionProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => RegionRoute,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountOrdersRoute,
} as any)
const AccountOrdersCodeRoute = AccountOrdersCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => AccountOrdersRoute,
} as any)
const CampaignSlugSplatRoute = CampaignSlugSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => CampaignSlugRoute,
} as any)
const RegionCampaignSlugSplatRoute = RegionCampaignSlugSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => RegionCampaignSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$region': typeof RegionRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/verify-pending': typeof VerifyPendingRoute
  '/wishlist': typeof WishlistRoute
  '/$region/account': typeof RegionAccountRoute
  '/$region/cart': typeof RegionCartRoute
  '/$region/checkout': typeof RegionCheckoutRoute
  '/$region/forgot-password': typeof RegionForgotPasswordRoute
  '/$region/register': typeof RegionRegisterRoute
  '/$region/reset-password': typeof RegionResetPasswordRoute
  '/$region/search': typeof RegionSearchRoute
  '/$region/shop': typeof RegionShopRoute
  '/$region/sign-in': typeof RegionSignInRoute
  '/$region/verify': typeof RegionVerifyRoute
  '/$region/verify-pending': typeof RegionVerifyPendingRoute
  '/$region/wishlist': typeof RegionWishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/profile': typeof AccountProfileRoute
  '/account/verify-email': typeof AccountVerifyEmailRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/campaign/$slug': typeof CampaignSlugRouteWithChildren
  '/collection/$slug': typeof CollectionSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/order-confirmation/$code': typeof OrderConfirmationCodeRoute
  '/product/$slug': typeof ProductSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/$region/': typeof RegionIndexRoute
  '/$region/campaign/$slug': typeof RegionCampaignSlugRouteWithChildren
  '/$region/collection/$slug': typeof RegionCollectionSlugRoute
  '/$region/collections/$slug': typeof RegionCollectionsSlugRoute
  '/$region/order-confirmation/$code': typeof RegionOrderConfirmationCodeRoute
  '/$region/product/$slug': typeof RegionProductSlugRoute
  '/$region/products/$slug': typeof RegionProductsSlugRoute
  '/account/orders/$code': typeof AccountOrdersCodeRoute
  '/campaign/$slug/$': typeof CampaignSlugSplatRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/$region/campaign/$slug/$': typeof RegionCampaignSlugSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/verify-pending': typeof VerifyPendingRoute
  '/wishlist': typeof WishlistRoute
  '/$region/account': typeof RegionAccountRoute
  '/$region/cart': typeof RegionCartRoute
  '/$region/checkout': typeof RegionCheckoutRoute
  '/$region/forgot-password': typeof RegionForgotPasswordRoute
  '/$region/register': typeof RegionRegisterRoute
  '/$region/reset-password': typeof RegionResetPasswordRoute
  '/$region/search': typeof RegionSearchRoute
  '/$region/shop': typeof RegionShopRoute
  '/$region/sign-in': typeof RegionSignInRoute
  '/$region/verify': typeof RegionVerifyRoute
  '/$region/verify-pending': typeof RegionVerifyPendingRoute
  '/$region/wishlist': typeof RegionWishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/verify-email': typeof AccountVerifyEmailRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/campaign/$slug': typeof CampaignSlugRouteWithChildren
  '/collection/$slug': typeof CollectionSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/order-confirmation/$code': typeof OrderConfirmationCodeRoute
  '/product/$slug': typeof ProductSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/$region': typeof RegionIndexRoute
  '/$region/campaign/$slug': typeof RegionCampaignSlugRouteWithChildren
  '/$region/collection/$slug': typeof RegionCollectionSlugRoute
  '/$region/collections/$slug': typeof RegionCollectionsSlugRoute
  '/$region/order-confirmation/$code': typeof RegionOrderConfirmationCodeRoute
  '/$region/product/$slug': typeof RegionProductSlugRoute
  '/$region/products/$slug': typeof RegionProductsSlugRoute
  '/account/orders/$code': typeof AccountOrdersCodeRoute
  '/campaign/$slug/$': typeof CampaignSlugSplatRoute
  '/account/orders': typeof AccountOrdersIndexRoute
  '/$region/campaign/$slug/$': typeof RegionCampaignSlugSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$region': typeof RegionRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify': typeof VerifyRoute
  '/verify-pending': typeof VerifyPendingRoute
  '/wishlist': typeof WishlistRoute
  '/$region/account': typeof RegionAccountRoute
  '/$region/cart': typeof RegionCartRoute
  '/$region/checkout': typeof RegionCheckoutRoute
  '/$region/forgot-password': typeof RegionForgotPasswordRoute
  '/$region/register': typeof RegionRegisterRoute
  '/$region/reset-password': typeof RegionResetPasswordRoute
  '/$region/search': typeof RegionSearchRoute
  '/$region/shop': typeof RegionShopRoute
  '/$region/sign-in': typeof RegionSignInRoute
  '/$region/verify': typeof RegionVerifyRoute
  '/$region/verify-pending': typeof RegionVerifyPendingRoute
  '/$region/wishlist': typeof RegionWishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/profile': typeof AccountProfileRoute
  '/account/verify-email': typeof AccountVerifyEmailRoute
  '/api/revalidate': typeof ApiRevalidateRoute
  '/campaign/$slug': typeof CampaignSlugRouteWithChildren
  '/collection/$slug': typeof CollectionSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/order-confirmation/$code': typeof OrderConfirmationCodeRoute
  '/product/$slug': typeof ProductSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/$region/': typeof RegionIndexRoute
  '/$region/campaign/$slug': typeof RegionCampaignSlugRouteWithChildren
  '/$region/collection/$slug': typeof RegionCollectionSlugRoute
  '/$region/collections/$slug': typeof RegionCollectionsSlugRoute
  '/$region/order-confirmation/$code': typeof RegionOrderConfirmationCodeRoute
  '/$region/product/$slug': typeof RegionProductSlugRoute
  '/$region/products/$slug': typeof RegionProductsSlugRoute
  '/account/orders/$code': typeof AccountOrdersCodeRoute
  '/campaign/$slug/$': typeof CampaignSlugSplatRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/$region/campaign/$slug/$': typeof RegionCampaignSlugSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$region'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/robots.txt'
    | '/search'
    | '/shop'
    | '/sign-in'
    | '/sitemap.xml'
    | '/verify'
    | '/verify-pending'
    | '/wishlist'
    | '/$region/account'
    | '/$region/cart'
    | '/$region/checkout'
    | '/$region/forgot-password'
    | '/$region/register'
    | '/$region/reset-password'
    | '/$region/search'
    | '/$region/shop'
    | '/$region/sign-in'
    | '/$region/verify'
    | '/$region/verify-pending'
    | '/$region/wishlist'
    | '/account/addresses'
    | '/account/orders'
    | '/account/profile'
    | '/account/verify-email'
    | '/api/revalidate'
    | '/campaign/$slug'
    | '/collection/$slug'
    | '/collections/$slug'
    | '/order-confirmation/$code'
    | '/product/$slug'
    | '/products/$slug'
    | '/$region/'
    | '/$region/campaign/$slug'
    | '/$region/collection/$slug'
    | '/$region/collections/$slug'
    | '/$region/order-confirmation/$code'
    | '/$region/product/$slug'
    | '/$region/products/$slug'
    | '/account/orders/$code'
    | '/campaign/$slug/$'
    | '/account/orders/'
    | '/$region/campaign/$slug/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/robots.txt'
    | '/search'
    | '/shop'
    | '/sign-in'
    | '/sitemap.xml'
    | '/verify'
    | '/verify-pending'
    | '/wishlist'
    | '/$region/account'
    | '/$region/cart'
    | '/$region/checkout'
    | '/$region/forgot-password'
    | '/$region/register'
    | '/$region/reset-password'
    | '/$region/search'
    | '/$region/shop'
    | '/$region/sign-in'
    | '/$region/verify'
    | '/$region/verify-pending'
    | '/$region/wishlist'
    | '/account/addresses'
    | '/account/profile'
    | '/account/verify-email'
    | '/api/revalidate'
    | '/campaign/$slug'
    | '/collection/$slug'
    | '/collections/$slug'
    | '/order-confirmation/$code'
    | '/product/$slug'
    | '/products/$slug'
    | '/$region'
    | '/$region/campaign/$slug'
    | '/$region/collection/$slug'
    | '/$region/collections/$slug'
    | '/$region/order-confirmation/$code'
    | '/$region/product/$slug'
    | '/$region/products/$slug'
    | '/account/orders/$code'
    | '/campaign/$slug/$'
    | '/account/orders'
    | '/$region/campaign/$slug/$'
  id:
    | '__root__'
    | '/'
    | '/$region'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/robots.txt'
    | '/search'
    | '/shop'
    | '/sign-in'
    | '/sitemap.xml'
    | '/verify'
    | '/verify-pending'
    | '/wishlist'
    | '/$region/account'
    | '/$region/cart'
    | '/$region/checkout'
    | '/$region/forgot-password'
    | '/$region/register'
    | '/$region/reset-password'
    | '/$region/search'
    | '/$region/shop'
    | '/$region/sign-in'
    | '/$region/verify'
    | '/$region/verify-pending'
    | '/$region/wishlist'
    | '/account/addresses'
    | '/account/orders'
    | '/account/profile'
    | '/account/verify-email'
    | '/api/revalidate'
    | '/campaign/$slug'
    | '/collection/$slug'
    | '/collections/$slug'
    | '/order-confirmation/$code'
    | '/product/$slug'
    | '/products/$slug'
    | '/$region/'
    | '/$region/campaign/$slug'
    | '/$region/collection/$slug'
    | '/$region/collections/$slug'
    | '/$region/order-confirmation/$code'
    | '/$region/product/$slug'
    | '/$region/products/$slug'
    | '/account/orders/$code'
    | '/campaign/$slug/$'
    | '/account/orders/'
    | '/$region/campaign/$slug/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegionRoute: typeof RegionRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  ShopRoute: typeof ShopRoute
  SignInRoute: typeof SignInRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerifyRoute: typeof VerifyRoute
  VerifyPendingRoute: typeof VerifyPendingRoute
  WishlistRoute: typeof WishlistRoute
  ApiRevalidateRoute: typeof ApiRevalidateRoute
  CampaignSlugRoute: typeof CampaignSlugRouteWithChildren
  CollectionSlugRoute: typeof CollectionSlugRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  OrderConfirmationCodeRoute: typeof OrderConfirmationCodeRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region': {
      id: '/$region'
      path: '/$region'
      fullPath: '/$region'
      preLoaderRoute: typeof RegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-pending': {
      id: '/verify-pending'
      path: '/verify-pending'
      fullPath: '/verify-pending'
      preLoaderRoute: typeof VerifyPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region/': {
      id: '/$region/'
      path: '/'
      fullPath: '/$region/'
      preLoaderRoute: typeof RegionIndexRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/account': {
      id: '/$region/account'
      path: '/account'
      fullPath: '/$region/account'
      preLoaderRoute: typeof RegionAccountRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/cart': {
      id: '/$region/cart'
      path: '/cart'
      fullPath: '/$region/cart'
      preLoaderRoute: typeof RegionCartRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/checkout': {
      id: '/$region/checkout'
      path: '/checkout'
      fullPath: '/$region/checkout'
      preLoaderRoute: typeof RegionCheckoutRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/forgot-password': {
      id: '/$region/forgot-password'
      path: '/forgot-password'
      fullPath: '/$region/forgot-password'
      preLoaderRoute: typeof RegionForgotPasswordRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/register': {
      id: '/$region/register'
      path: '/register'
      fullPath: '/$region/register'
      preLoaderRoute: typeof RegionRegisterRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/reset-password': {
      id: '/$region/reset-password'
      path: '/reset-password'
      fullPath: '/$region/reset-password'
      preLoaderRoute: typeof RegionResetPasswordRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/search': {
      id: '/$region/search'
      path: '/search'
      fullPath: '/$region/search'
      preLoaderRoute: typeof RegionSearchRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/shop': {
      id: '/$region/shop'
      path: '/shop'
      fullPath: '/$region/shop'
      preLoaderRoute: typeof RegionShopRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/sign-in': {
      id: '/$region/sign-in'
      path: '/sign-in'
      fullPath: '/$region/sign-in'
      preLoaderRoute: typeof RegionSignInRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/verify': {
      id: '/$region/verify'
      path: '/verify'
      fullPath: '/$region/verify'
      preLoaderRoute: typeof RegionVerifyRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/verify-pending': {
      id: '/$region/verify-pending'
      path: '/verify-pending'
      fullPath: '/$region/verify-pending'
      preLoaderRoute: typeof RegionVerifyPendingRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/wishlist': {
      id: '/$region/wishlist'
      path: '/wishlist'
      fullPath: '/$region/wishlist'
      preLoaderRoute: typeof RegionWishlistRouteImport
      parentRoute: typeof RegionRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/verify-email': {
      id: '/account/verify-email'
      path: '/verify-email'
      fullPath: '/account/verify-email'
      preLoaderRoute: typeof AccountVerifyEmailRouteImport
      parentRoute: typeof AccountRoute
    }
    '/api/revalidate': {
      id: '/api/revalidate'
      path: '/api/revalidate'
      fullPath: '/api/revalidate'
      preLoaderRoute: typeof ApiRevalidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign/$slug': {
      id: '/campaign/$slug'
      path: '/campaign/$slug'
      fullPath: '/campaign/$slug'
      preLoaderRoute: typeof CampaignSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$slug': {
      id: '/collection/$slug'
      path: '/collection/$slug'
      fullPath: '/collection/$slug'
      preLoaderRoute: typeof CollectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation/$code': {
      id: '/order-confirmation/$code'
      path: '/order-confirmation/$code'
      fullPath: '/order-confirmation/$code'
      preLoaderRoute: typeof OrderConfirmationCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region/campaign/$slug': {
      id: '/$region/campaign/$slug'
      path: '/campaign/$slug'
      fullPath: '/$region/campaign/$slug'
      preLoaderRoute: typeof RegionCampaignSlugRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/collection/$slug': {
      id: '/$region/collection/$slug'
      path: '/collection/$slug'
      fullPath: '/$region/collection/$slug'
      preLoaderRoute: typeof RegionCollectionSlugRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/collections/$slug': {
      id: '/$region/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/$region/collections/$slug'
      preLoaderRoute: typeof RegionCollectionsSlugRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/order-confirmation/$code': {
      id: '/$region/order-confirmation/$code'
      path: '/order-confirmation/$code'
      fullPath: '/$region/order-confirmation/$code'
      preLoaderRoute: typeof RegionOrderConfirmationCodeRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/product/$slug': {
      id: '/$region/product/$slug'
      path: '/product/$slug'
      fullPath: '/$region/product/$slug'
      preLoaderRoute: typeof RegionProductSlugRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/products/$slug': {
      id: '/$region/products/$slug'
      path: '/products/$slug'
      fullPath: '/$region/products/$slug'
      preLoaderRoute: typeof RegionProductsSlugRouteImport
      parentRoute: typeof RegionRoute
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
    '/account/orders/$code': {
      id: '/account/orders/$code'
      path: '/$code'
      fullPath: '/account/orders/$code'
      preLoaderRoute: typeof AccountOrdersCodeRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
    '/campaign/$slug/$': {
      id: '/campaign/$slug/$'
      path: '/$'
      fullPath: '/campaign/$slug/$'
      preLoaderRoute: typeof CampaignSlugSplatRouteImport
      parentRoute: typeof CampaignSlugRoute
    }
    '/$region/campaign/$slug/$': {
      id: '/$region/campaign/$slug/$'
      path: '/$'
      fullPath: '/$region/campaign/$slug/$'
      preLoaderRoute: typeof RegionCampaignSlugSplatRouteImport
      parentRoute: typeof RegionCampaignSlugRoute
    }
  }
}

interface RegionCampaignSlugRouteChildren {
  RegionCampaignSlugSplatRoute: typeof RegionCampaignSlugSplatRoute
}

const RegionCampaignSlugRouteChildren: RegionCampaignSlugRouteChildren = {
  RegionCampaignSlugSplatRoute: RegionCampaignSlugSplatRoute,
}

const RegionCampaignSlugRouteWithChildren =
  RegionCampaignSlugRoute._addFileChildren(RegionCampaignSlugRouteChildren)

interface RegionRouteChildren {
  RegionAccountRoute: typeof RegionAccountRoute
  RegionCartRoute: typeof RegionCartRoute
  RegionCheckoutRoute: typeof RegionCheckoutRoute
  RegionForgotPasswordRoute: typeof RegionForgotPasswordRoute
  RegionRegisterRoute: typeof RegionRegisterRoute
  RegionResetPasswordRoute: typeof RegionResetPasswordRoute
  RegionSearchRoute: typeof RegionSearchRoute
  RegionShopRoute: typeof RegionShopRoute
  RegionSignInRoute: typeof RegionSignInRoute
  RegionVerifyRoute: typeof RegionVerifyRoute
  RegionVerifyPendingRoute: typeof RegionVerifyPendingRoute
  RegionWishlistRoute: typeof RegionWishlistRoute
  RegionIndexRoute: typeof RegionIndexRoute
  RegionCampaignSlugRoute: typeof RegionCampaignSlugRouteWithChildren
  RegionCollectionSlugRoute: typeof RegionCollectionSlugRoute
  RegionCollectionsSlugRoute: typeof RegionCollectionsSlugRoute
  RegionOrderConfirmationCodeRoute: typeof RegionOrderConfirmationCodeRoute
  RegionProductSlugRoute: typeof RegionProductSlugRoute
  RegionProductsSlugRoute: typeof RegionProductsSlugRoute
}

const RegionRouteChildren: RegionRouteChildren = {
  RegionAccountRoute: RegionAccountRoute,
  RegionCartRoute: RegionCartRoute,
  RegionCheckoutRoute: RegionCheckoutRoute,
  RegionForgotPasswordRoute: RegionForgotPasswordRoute,
  RegionRegisterRoute: RegionRegisterRoute,
  RegionResetPasswordRoute: RegionResetPasswordRoute,
  RegionSearchRoute: RegionSearchRoute,
  RegionShopRoute: RegionShopRoute,
  RegionSignInRoute: RegionSignInRoute,
  RegionVerifyRoute: RegionVerifyRoute,
  RegionVerifyPendingRoute: RegionVerifyPendingRoute,
  RegionWishlistRoute: RegionWishlistRoute,
  RegionIndexRoute: RegionIndexRoute,
  RegionCampaignSlugRoute: RegionCampaignSlugRouteWithChildren,
  RegionCollectionSlugRoute: RegionCollectionSlugRoute,
  RegionCollectionsSlugRoute: RegionCollectionsSlugRoute,
  RegionOrderConfirmationCodeRoute: RegionOrderConfirmationCodeRoute,
  RegionProductSlugRoute: RegionProductSlugRoute,
  RegionProductsSlugRoute: RegionProductsSlugRoute,
}

const RegionRouteWithChildren =
  RegionRoute._addFileChildren(RegionRouteChildren)

interface AccountOrdersRouteChildren {
  AccountOrdersCodeRoute: typeof AccountOrdersCodeRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersCodeRoute: AccountOrdersCodeRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
  AccountProfileRoute: typeof AccountProfileRoute
  AccountVerifyEmailRoute: typeof AccountVerifyEmailRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
  AccountProfileRoute: AccountProfileRoute,
  AccountVerifyEmailRoute: AccountVerifyEmailRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface CampaignSlugRouteChildren {
  CampaignSlugSplatRoute: typeof CampaignSlugSplatRoute
}

const CampaignSlugRouteChildren: CampaignSlugRouteChildren = {
  CampaignSlugSplatRoute: CampaignSlugSplatRoute,
}

const CampaignSlugRouteWithChildren = CampaignSlugRoute._addFileChildren(
  CampaignSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegionRoute: RegionRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  ShopRoute: ShopRoute,
  SignInRoute: SignInRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerifyRoute: VerifyRoute,
  VerifyPendingRoute: VerifyPendingRoute,
  WishlistRoute: WishlistRoute,
  ApiRevalidateRoute: ApiRevalidateRoute,
  CampaignSlugRoute: CampaignSlugRouteWithChildren,
  CollectionSlugRoute: CollectionSlugRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  OrderConfirmationCodeRoute: OrderConfirmationCodeRoute,
  ProductSlugRoute: ProductSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
