export interface CountryMetadata {
    countryCode: string;
    countryName: string;
    flag: string;
    currencyCode: string;
    currencySymbol: string;
    callingCode: string;
    defaultLanguage: string;
    continent: string;
    isEuropeanUnion: boolean;
}

export const COUNTRY_METADATA_REGISTRY: Record<string, CountryMetadata> = {
    BD: {
        countryCode: 'BD',
        countryName: 'Bangladesh',
        flag: '🇧🇩',
        currencyCode: 'BDT',
        currencySymbol: '৳',
        callingCode: '+880',
        defaultLanguage: 'bn',
        continent: 'AS',
        isEuropeanUnion: false,
    },
    IN: {
        countryCode: 'IN',
        countryName: 'India',
        flag: '🇮🇳',
        currencyCode: 'INR',
        currencySymbol: '₹',
        callingCode: '+91',
        defaultLanguage: 'hi',
        continent: 'AS',
        isEuropeanUnion: false,
    },
    AE: {
        countryCode: 'AE',
        countryName: 'United Arab Emirates',
        flag: '🇦🇪',
        currencyCode: 'AED',
        currencySymbol: 'د.إ',
        callingCode: '+971',
        defaultLanguage: 'ar',
        continent: 'AS',
        isEuropeanUnion: false,
    },
    US: {
        countryCode: 'US',
        countryName: 'United States',
        flag: '🇺🇸',
        currencyCode: 'USD',
        currencySymbol: '$',
        callingCode: '+1',
        defaultLanguage: 'en',
        continent: 'NA',
        isEuropeanUnion: false,
    },
    GB: {
        countryCode: 'GB',
        countryName: 'United Kingdom',
        flag: '🇬🇧',
        currencyCode: 'GBP',
        currencySymbol: '£',
        callingCode: '+44',
        defaultLanguage: 'en',
        continent: 'EU',
        isEuropeanUnion: false,
    },
    CA: {
        countryCode: 'CA',
        countryName: 'Canada',
        flag: '🇨🇦',
        currencyCode: 'CAD',
        currencySymbol: '$',
        callingCode: '+1',
        defaultLanguage: 'en',
        continent: 'NA',
        isEuropeanUnion: false,
    },
    AU: {
        countryCode: 'AU',
        countryName: 'Australia',
        flag: '🇦🇺',
        currencyCode: 'AUD',
        currencySymbol: '$',
        callingCode: '+61',
        defaultLanguage: 'en',
        continent: 'OC',
        isEuropeanUnion: false,
    },
    SG: {
        countryCode: 'SG',
        countryName: 'Singapore',
        flag: '🇸🇬',
        currencyCode: 'SGD',
        currencySymbol: '$',
        callingCode: '+65',
        defaultLanguage: 'en',
        continent: 'AS',
        isEuropeanUnion: false,
    },
    MY: {
        countryCode: 'MY',
        countryName: 'Malaysia',
        flag: '🇲🇾',
        currencyCode: 'MYR',
        currencySymbol: 'RM',
        callingCode: '+60',
        defaultLanguage: 'ms',
        continent: 'AS',
        isEuropeanUnion: false,
    },
    SA: {
        countryCode: 'SA',
        countryName: 'Saudi Arabia',
        flag: '🇸🇦',
        currencyCode: 'SAR',
        currencySymbol: '﷼',
        callingCode: '+966',
        defaultLanguage: 'ar',
        continent: 'AS',
        isEuropeanUnion: false,
    },
    QA: {
        countryCode: 'QA',
        countryName: 'Qatar',
        flag: '🇶🇦',
        currencyCode: 'QAR',
        currencySymbol: '﷼',
        callingCode: '+974',
        defaultLanguage: 'ar',
        continent: 'AS',
        isEuropeanUnion: false,
    },
    KW: {
        countryCode: 'KW',
        countryName: 'Kuwait',
        flag: '🇰🇼',
        currencyCode: 'KWD',
        currencySymbol: 'د.ك',
        callingCode: '+965',
        defaultLanguage: 'ar',
        continent: 'AS',
        isEuropeanUnion: false,
    },
    OM: {
        countryCode: 'OM',
        countryName: 'Oman',
        flag: '🇴🇲',
        currencyCode: 'OMR',
        currencySymbol: 'ر.ع.',
        callingCode: '+968',
        defaultLanguage: 'ar',
        continent: 'AS',
        isEuropeanUnion: false,
    },
    BH: {
        countryCode: 'BH',
        countryName: 'Bahrain',
        flag: '🇧🇭',
        currencyCode: 'BHD',
        currencySymbol: '.د.ب',
        callingCode: '+973',
        defaultLanguage: 'ar',
        continent: 'AS',
        isEuropeanUnion: false,
    },
    DE: {
        countryCode: 'DE',
        countryName: 'Germany',
        flag: '🇩🇪',
        currencyCode: 'EUR',
        currencySymbol: '€',
        callingCode: '+49',
        defaultLanguage: 'de',
        continent: 'EU',
        isEuropeanUnion: true,
    },
    FR: {
        countryCode: 'FR',
        countryName: 'France',
        flag: '🇫🇷',
        currencyCode: 'EUR',
        currencySymbol: '€',
        callingCode: '+33',
        defaultLanguage: 'fr',
        continent: 'EU',
        isEuropeanUnion: true,
    },
    IT: {
        countryCode: 'IT',
        countryName: 'Italy',
        flag: '🇮🇹',
        currencyCode: 'EUR',
        currencySymbol: '€',
        callingCode: '+39',
        defaultLanguage: 'it',
        continent: 'EU',
        isEuropeanUnion: true,
    },
    ES: {
        countryCode: 'ES',
        countryName: 'Spain',
        flag: '🇪🇸',
        currencyCode: 'EUR',
        currencySymbol: '€',
        callingCode: '+34',
        defaultLanguage: 'es',
        continent: 'EU',
        isEuropeanUnion: true,
    },
    NL: {
        countryCode: 'NL',
        countryName: 'Netherlands',
        flag: '🇳🇱',
        currencyCode: 'EUR',
        currencySymbol: '€',
        callingCode: '+31',
        defaultLanguage: 'nl',
        continent: 'EU',
        isEuropeanUnion: true,
    },
    CH: {
        countryCode: 'CH',
        countryName: 'Switzerland',
        flag: '🇨🇭',
        currencyCode: 'CHF',
        currencySymbol: 'CHF',
        callingCode: '+41',
        defaultLanguage: 'de',
        continent: 'EU',
        isEuropeanUnion: false,
    },
    SE: {
        countryCode: 'SE',
        countryName: 'Sweden',
        flag: '🇸🇪',
        currencyCode: 'SEK',
        currencySymbol: 'kr',
        callingCode: '+46',
        defaultLanguage: 'sv',
        continent: 'EU',
        isEuropeanUnion: true,
    },
    NO: {
        countryCode: 'NO',
        countryName: 'Norway',
        flag: '🇳🇴',
        currencyCode: 'NOK',
        currencySymbol: 'kr',
        callingCode: '+47',
        defaultLanguage: 'no',
        continent: 'EU',
        isEuropeanUnion: false,
    },
    JP: {
        countryCode: 'JP',
        countryName: 'Japan',
        flag: '🇯🇵',
        currencyCode: 'JPY',
        currencySymbol: '¥',
        callingCode: '+81',
        defaultLanguage: 'ja',
        continent: 'AS',
        isEuropeanUnion: false,
    },
    KR: {
        countryCode: 'KR',
        countryName: 'South Korea',
        flag: '🇰🇷',
        currencyCode: 'KRW',
        currencySymbol: '₩',
        callingCode: '+82',
        defaultLanguage: 'ko',
        continent: 'AS',
        isEuropeanUnion: false,
    },
    NZ: {
        countryCode: 'NZ',
        countryName: 'New Zealand',
        flag: '🇳🇿',
        currencyCode: 'NZD',
        currencySymbol: '$',
        callingCode: '+64',
        defaultLanguage: 'en',
        continent: 'OC',
        isEuropeanUnion: false,
    },
    ZA: {
        countryCode: 'ZA',
        countryName: 'South Africa',
        flag: '🇿🇦',
        currencyCode: 'ZAR',
        currencySymbol: 'R',
        callingCode: '+27',
        defaultLanguage: 'en',
        continent: 'AF',
        isEuropeanUnion: false,
    },
    BR: {
        countryCode: 'BR',
        countryName: 'Brazil',
        flag: '🇧🇷',
        currencyCode: 'BRL',
        currencySymbol: 'R$',
        callingCode: '+55',
        defaultLanguage: 'pt',
        continent: 'SA',
        isEuropeanUnion: false,
    },
    MX: {
        countryCode: 'MX',
        countryName: 'Mexico',
        flag: '🇲🇽',
        currencyCode: 'MXN',
        currencySymbol: '$',
        callingCode: '+52',
        defaultLanguage: 'es',
        continent: 'NA',
        isEuropeanUnion: false,
    },
};

/**
 * Returns regional metadata for an ISO 3166-1 alpha-2 country code.
 * If not in the high-priority registry, falls back to a deterministic safe object.
 */
export function getCountryMetadata(code: string | null | undefined): CountryMetadata | null {
    if (!code || typeof code !== 'string') return null;
    const clean = code.trim().toUpperCase();
    if (clean.length !== 2) return null;

    if (COUNTRY_METADATA_REGISTRY[clean]) {
        return COUNTRY_METADATA_REGISTRY[clean];
    }

    // Dynamic fallback for any valid ISO code
    return {
        countryCode: clean,
        countryName: clean,
        flag: '🌐',
        currencyCode: 'USD',
        currencySymbol: '$',
        callingCode: '',
        defaultLanguage: 'en',
        continent: 'GL',
        isEuropeanUnion: false,
    };
}
